import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='h-full'>
      <body className='p-6 h-full'>
        <main className='border border-solid border-dark rounded-lg h-full bg-primary'>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
